# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      # fail-fast: false
      matrix:
        # Python 3.4  # EOL 2019-03-18
        # Python 3.5  # EOL 2020-09-13
        # Python 3.6  # EOL 2021-12-21
        # Python 3.7  # EOL 2023-06-27
        # Python 3.8  # EOL 2024-10
        # Python 3.9  # EOL 2025-10
        # Python 3.10 # EOL 2026-10
        # Python 3.11 # EOL 2027-10
        # Python 3.12 # EOL 2028-10
        # Python 3.13 # EOL 2029-10
        # Python 3.14 # EOL 2030-10
        # Python 3.15 # EOL 2031-10
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14", "3.15"]

    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-dev libxslt1-dev

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Install dependencies
        run: |
          uv python install ${{ matrix.python-version }}
          uv sync --no-dev
          uv pip install cheroot defusedxml Jinja2 json5 PyYAML pytest pytest-cov pytest-html redis requests ruff webtest

      - name: Lint with ruff
        run: |
          uv run ruff -V
          uv run ruff check wsgidav tests

      - name: Test with pytest
        run: |
          uv run pytest -V
          uv run pytest -ra -v -x --durations=10 --cov=wsgidav

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
